### ISSUE TITLE
Error on dwg file

### ISSUE THREAD

**Issue by efsjouw** [harvard-lts/cadtool#10]
Hello no idea if this is too old but I have an error.

**command**
`fits cadtool -i amb11.dwg -o amb11output`

**error**
```
2020-03-12 15:58:39 - ERROR - Fits:677 - Tool error processing file: amb11.dwg
edu.harvard.hul.ois.fits.tools.ToolOutput.<init>(Ledu/harvard/hul/ois/fits/tools/Tool;Lorg/jdom/Document;Lorg/jdom/Document;)V
java.lang.NoSuchMethodError: edu.harvard.hul.ois.fits.tools.ToolOutput.<init>(Ledu/harvard/hul/ois/fits/tools/Tool;Lorg/jdom/Document;Lorg/jdom/Document;)V
        at edu.harvard.hul.ois.fits.tools.cad.CadTool.extractInfo(CadTool.java:127)
        at edu.harvard.hul.ois.fits.tools.cad.CadTool.extractInfo(CadTool.java:132)
        at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:284)
        at java.base/java.lang.Thread.run(Unknown Source)
```

any ideas?

**Comment by daveneiman** [comment]
Yes, this is likely very old. From which branch did you pull the code?

**Comment by efsjouw** [comment]
Actually I downloaded the release.

**Comment by daveneiman** [comment]
Sorry for the delay getting back to you. Yes, this branch, cadtool, is VERY old and has not been brought up to date with the rest of the code. At the time we were starting work on handling CAD documents but that effort came to a halt. Since then there have been significant changes to the code. At some point in the future we will take up this branch again. In the mean time I'm afraid we are unable to provide support for it.
